name: Generate Snake Animation 🐍

on:
  # Executa automaticamente a cada 24h
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar manualmente no GitHub
  workflow_dispatch:

  # Executa sempre que houver push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      # Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera os arquivos SVG com a cobrinha animada
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          snake_color: '#00FF00'  # verde neon
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica os arquivos na branch `output`
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
